Repository Team-inglo/Giggle-Server, pull requests merged in 2024-10, with the labels that each got.

#23 ✨ Feature - Account 그룹(3번대 API) 구현
  http/account/AccountControllerHttpRequest.http
  http/auth/AuthControllerHttpRequest.http
  src/main/java/com/inglo/giggle/GiggleSeverApplication.java
  src/main/java/com/inglo/giggle/account/application/controller/command/.keep
  src/main/java/com/inglo/giggle/account/application/controller/command/AccountCommandV1Controller.java
  src/main/java/com/inglo/giggle/account/application/controller/command/AccountOwnersCommandV1Controller.java
  src/main/java/com/inglo/giggle/account/application/controller/command/AccountUsersCommandV1Controller.java
  src/main/java/com/inglo/giggle/account/application/controller/query/.keep
  src/main/java/com/inglo/giggle/account/application/controller/query/AccountOwnersQueryV1Controller.java
  src/main/java/com/inglo/giggle/account/application/controller/query/AccountUsersQueryV1Controller.java
  src/main/java/com/inglo/giggle/account/application/dto/request/.keep
  src/main/java/com/inglo/giggle/account/application/dto/request/UpdateNotificationAllowedRequestDto.java
  src/main/java/com/inglo/giggle/account/application/dto/request/UpdateOwnerRequestDto.java
  src/main/java/com/inglo/giggle/account/application/dto/request/UpdateUserLanguageRequestDto.java
  src/main/java/com/inglo/giggle/account/application/dto/request/UpdateUserRequestDto.java
  src/main/java/com/inglo/giggle/account/application/dto/response/.keep
  src/main/java/com/inglo/giggle/account/application/dto/response/ReadOwnerBriefResponseDto.java
  src/main/java/com/inglo/giggle/account/application/dto/response/ReadOwnerDetailResponseDto.java
  src/main/java/com/inglo/giggle/account/application/dto/response/ReadUserDetailResponseDto.java
  src/main/java/com/inglo/giggle/account/application/dto/response/ReadUserSummaryResponseDto.java
  src/main/java/com/inglo/giggle/account/application/service/.keep
  src/main/java/com/inglo/giggle/account/application/service/ReadOwnerBriefService.java
  src/main/java/com/inglo/giggle/account/application/service/ReadOwnerDetailService.java
  src/main/java/com/inglo/giggle/account/application/service/ReadUserDetailService.java
  src/main/java/com/inglo/giggle/account/application/service/ReadUserSummaryService.java
  src/main/java/com/inglo/giggle/account/application/service/UpdateNotificationAllowedService.java
  src/main/java/com/inglo/giggle/account/application/service/UpdateOwnerService.java
  src/main/java/com/inglo/giggle/account/application/service/UpdateUserLanguageService.java
  src/main/java/com/inglo/giggle/account/application/service/UpdateUserService.java
  src/main/java/com/inglo/giggle/account/application/usecase/.keep
  src/main/java/com/inglo/giggle/account/application/usecase/ReadOwnerBriefUseCase.java
  src/main/java/com/inglo/giggle/account/application/usecase/ReadOwnerDetailUseCase.java
  src/main/java/com/inglo/giggle/account/application/usecase/ReadUserDetailUseCase.java
  src/main/java/com/inglo/giggle/account/application/usecase/ReadUserSummaryUseCase.java
  src/main/java/com/inglo/giggle/account/application/usecase/UpdateNotificationAllowedUseCase.java
  src/main/java/com/inglo/giggle/account/application/usecase/UpdateOwnerUseCase.java
  src/main/java/com/inglo/giggle/account/application/usecase/UpdateUserLanguageUseCase.java
  src/main/java/com/inglo/giggle/account/application/usecase/UpdateUserUseCase.java
  src/main/java/com/inglo/giggle/account/domain/Owner.java
  src/main/java/com/inglo/giggle/account/domain/User.java
  src/main/java/com/inglo/giggle/account/domain/service/OwnerService.java
  src/main/java/com/inglo/giggle/account/domain/service/UserService.java
  src/main/java/com/inglo/giggle/address/domain/Address.java
  src/main/java/com/inglo/giggle/address/domain/service/AddressService.java
  src/main/java/com/inglo/giggle/core/type/EEducationLevel.java
  src/main/java/com/inglo/giggle/core/type/EVisa.java
  src/main/java/com/inglo/giggle/resume/domain/service/EducationService.java
  src/main/java/com/inglo/giggle/resume/repository/mysql/EducationRepository.java
  src/main/java/com/inglo/giggle/security/domain/mysql/Account.java
  src/main/java/com/inglo/giggle/security/domain/service/AccountService.java
Labels: ✨ Feature, 🐾 dongkyeomjang

#26 🌏 Deploy - redis 연결을 위한 docker network 추가
  .github/workflows/dev-cicd.yml
Labels: 🌏 Deploy, 🐾 dongkyeomjang

#28 🐞 BugFix - 로그인 시 access token이 쿠키로 넘어가는 버그
  src/main/java/com/inglo/giggle/security/handler/login/DefaultLoginSuccessHandler.java
Labels: 🐞 BugFix, 🐾 dongkyeomjang

#31 ✨ Feature - School 그룹(9번대 API) 구현
  http/school/SchoolControllerHttpRequest.http
  src/main/java/com/inglo/giggle/document/application/dto/response/ReadOwnerDocumentSummaryResponseDto.java
  src/main/java/com/inglo/giggle/document/application/service/ReadOwnerDocumentSummaryService.java
  src/main/java/com/inglo/giggle/resume/repository/mysql/EducationRepository.java
  src/main/java/com/inglo/giggle/school/application/controller/query/.keep
  src/main/java/com/inglo/giggle/school/application/controller/query/SchoolUsersQueryV1Controller.java
  src/main/java/com/inglo/giggle/school/application/dto/response/.keep
  src/main/java/com/inglo/giggle/school/application/dto/response/ReadUserSchoolBriefResponseDto.java
  src/main/java/com/inglo/giggle/school/application/dto/response/ReadUserSchoolDetailResponseDto.java
  src/main/java/com/inglo/giggle/school/application/service/.keep
  src/main/java/com/inglo/giggle/school/application/service/ReadUserSchoolBriefService.java
  src/main/java/com/inglo/giggle/school/application/service/ReadUserSchoolDetailService.java
  src/main/java/com/inglo/giggle/school/application/usecase/.keep
  src/main/java/com/inglo/giggle/school/application/usecase/ReadUserSchoolBriefUseCase.java
  src/main/java/com/inglo/giggle/school/application/usecase/ReadUserSchoolDetailUseCase.java
  src/main/java/com/inglo/giggle/school/domain/School.java
  src/main/java/com/inglo/giggle/school/repository/mysql/SchoolRepository.java
Labels: ✨ Feature, 🐾 dongkyeomjang

#34 🐞 BugFix - User 프로필 수정에서의 버그, 프로필 이미지 조회 버그 수정
  src/main/java/com/inglo/giggle/account/application/dto/request/UpdateUserRequestDto.java
  src/main/java/com/inglo/giggle/account/application/dto/response/ReadUserDetailResponseDto.java
  src/main/java/com/inglo/giggle/account/domain/User.java
  src/main/java/com/inglo/giggle/account/domain/service/UserService.java
Labels: 🐞 BugFix, 🐾 dongkyeomjang

#39 🐞 BugFix - 6.4 Invalid EndPoint Bug 해결
  http/posting/PostControllerHttpRequest.http
  src/main/java/com/inglo/giggle/posting/application/controller/query/PostingUsersQueryV1Controller.java
Labels: 🐞 BugFix, 🐾 dongkyeomjang

#41 🐞 BugFix - 7.1 Null값에 대한 처리 , 7.3 size 수정 , 7.4 오타수정
  src/main/java/com/inglo/giggle/resume/application/dto/request/CreateUserWorkExperienceRequestDto.java
  src/main/java/com/inglo/giggle/resume/application/dto/request/UpdateUserWorkExperienceRequestDto.java
  src/main/java/com/inglo/giggle/resume/application/dto/response/ReadUserLanguageSummaryResponseDto.java
  src/main/java/com/inglo/giggle/resume/application/dto/response/ReadUserResumeDetailResponseDto.java
  src/main/java/com/inglo/giggle/resume/domain/WorkExperience.java
Labels: 🐞 BugFix, 🐾 dongkyeomjang

#44 🐞 BugFix - 7.7 miss endpoint, 7.1 null point exception
  http/resume/ResumeControllerHttpRequest.http
  src/main/java/com/inglo/giggle/resume/application/controller/command/ResumeUsersCommandV1Controller.java
  src/main/java/com/inglo/giggle/resume/application/dto/response/ReadUserResumeDetailResponseDto.java
Labels: 🐞 BugFix, 🐾 dongkyeomjang

#45 🐞 BugFix - 7.7 miss endpoint, 7.1 null point exception (RE)
  src/main/java/com/inglo/giggle/resume/application/dto/response/ReadUserResumeDetailResponseDto.java
Labels: 🐞 BugFix, 🐾 dongkyeomjang

#46 🐞 BugFix - 7.7 miss endpoint, 7.1 null point exception (RE-2)
  src/main/java/com/inglo/giggle/resume/application/dto/response/ReadOwnerResumeDetailResponseDto.java
  src/main/java/com/inglo/giggle/resume/application/dto/response/ReadUserEducationDetailResponseDto.java
  src/main/java/com/inglo/giggle/resume/application/dto/response/ReadUserLanguageSummaryResponseDto.java
  src/main/java/com/inglo/giggle/resume/application/dto/response/ReadUserResumeDetailResponseDto.java
  src/main/java/com/inglo/giggle/resume/application/dto/response/ReadUserWorkExperienceDetailResponseDto.java
Labels: 🐞 BugFix, 🐾 dongkyeomjang

#47 🐞 BugFix - 7.18 miss endpoint 수정
  http/resume/ResumeControllerHttpRequest.http
  src/main/java/com/inglo/giggle/resume/application/controller/command/ResumeUsersCommandV1Controller.java
  src/main/java/com/inglo/giggle/resume/application/dto/response/ReadOwnerResumeDetailResponseDto.java
Labels: 🐞 BugFix, 🐾 dongkyeomjang

#49 🔨 Refactor - 코드 리펙토링 및 주석 추가
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadGuestJobPostingDetailResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadJobPostingDetailResponseDto.java
  src/main/java/com/inglo/giggle/posting/domain/service/UserOwnerJobPostingService.java
  src/main/java/com/inglo/giggle/resume/application/controller/command/ResumeUsersCommandV1Controller.java
  src/main/java/com/inglo/giggle/resume/application/controller/query/ResumeOwnersQueryV1Controller.java
  src/main/java/com/inglo/giggle/resume/application/controller/query/ResumeUsersQueryV1Controller.java
  src/main/java/com/inglo/giggle/resume/application/service/CreateUserAdditionalLanguageSkillService.java
  src/main/java/com/inglo/giggle/resume/application/service/CreateUserEducationService.java
  src/main/java/com/inglo/giggle/resume/application/service/CreateUserWorkExperienceService.java
  src/main/java/com/inglo/giggle/resume/application/service/DeleteUserAdditionalLanguageService.java
  src/main/java/com/inglo/giggle/resume/application/service/DeleteUserEducationService.java
  src/main/java/com/inglo/giggle/resume/application/service/DeleteUserIntroductionService.java
  src/main/java/com/inglo/giggle/resume/application/service/DeleteUserWorkExperienceService.java
  src/main/java/com/inglo/giggle/resume/application/service/ReadOwnerResumeDetailService.java
  src/main/java/com/inglo/giggle/resume/application/service/ReadUserEducationDetailService.java
  src/main/java/com/inglo/giggle/resume/application/service/ReadUserLanguageSummaryService.java
  src/main/java/com/inglo/giggle/resume/application/service/ReadUserResumeDetailService.java
  src/main/java/com/inglo/giggle/resume/application/service/ReadUserWorkExperienceDetailService.java
  src/main/java/com/inglo/giggle/resume/application/service/UpdateUserAdditionalLanguageSkillService.java
  src/main/java/com/inglo/giggle/resume/application/service/UpdateUserEducationService.java
  src/main/java/com/inglo/giggle/resume/application/service/UpdateUserIntroductionService.java
  src/main/java/com/inglo/giggle/resume/application/service/UpdateUserSejongInstituteService.java
  src/main/java/com/inglo/giggle/resume/application/service/UpdateUserSocialIntegrationProgramService.java
  src/main/java/com/inglo/giggle/resume/application/service/UpdateUserTopikService.java
  src/main/java/com/inglo/giggle/resume/application/service/UpdateUserWorkExperienceService.java
  src/main/java/com/inglo/giggle/resume/application/usecase/DeleteUserAdditionalLanguageUseCase.java
  src/main/java/com/inglo/giggle/resume/application/usecase/DeleteUserEducationUseCase.java
  src/main/java/com/inglo/giggle/resume/application/usecase/DeleteUserWorkExperienceUseCase.java
  src/main/java/com/inglo/giggle/resume/application/usecase/ReadOwnerResumeDetailUseCase.java
  src/main/java/com/inglo/giggle/resume/application/usecase/ReadUserEducationDetailUseCase.java
  src/main/java/com/inglo/giggle/resume/application/usecase/ReadUserWorkExperienceDetailUseCase.java
  src/main/java/com/inglo/giggle/resume/application/usecase/UpdateUserAdditionalLanguageSkillUseCase.java
  src/main/java/com/inglo/giggle/resume/application/usecase/UpdateUserEducationUseCase.java
  src/main/java/com/inglo/giggle/resume/application/usecase/UpdateUserWorkExperienceUseCase.java
  src/main/java/com/inglo/giggle/resume/domain/service/AdditionalLanguageService.java
  src/main/java/com/inglo/giggle/resume/domain/service/EducationService.java
  src/main/java/com/inglo/giggle/resume/domain/service/LanguageSkillService.java
  src/main/java/com/inglo/giggle/resume/domain/service/ResumeService.java
  src/main/java/com/inglo/giggle/resume/domain/service/WorkExperienceService.java
  src/main/java/com/inglo/giggle/resume/repository/mysql/AdditionalLanguageRepository.java
  src/main/java/com/inglo/giggle/security/domain/service/AccountService.java
Labels: 🔨 Refactor, 🐾 dongkyeomjang

#52 🔨 Refactor - 코드 리펙토링 및 주석 추가
  src/main/java/com/inglo/giggle/account/domain/Owner.java
  src/main/java/com/inglo/giggle/document/application/controller/command/DocumentOwnersCommandV1Controller.java
  src/main/java/com/inglo/giggle/document/application/controller/command/DocumentUsersCommandV1Controller.java
  src/main/java/com/inglo/giggle/document/application/controller/query/DocumentQueryV1Controller.java
  src/main/java/com/inglo/giggle/document/application/service/ConfirmUserDocumentService.java
  src/main/java/com/inglo/giggle/document/application/service/CreateUserIntegratedApplicationService.java
  src/main/java/com/inglo/giggle/document/application/service/CreateUserPartTimeEmploymentPermitService.java
  src/main/java/com/inglo/giggle/document/application/service/CreateUserStandardLaborContractService.java
  src/main/java/com/inglo/giggle/document/application/service/ReadIntegratedApplicationDetailService.java
  src/main/java/com/inglo/giggle/document/application/service/ReadOwnerDocumentSummaryService.java
  src/main/java/com/inglo/giggle/document/application/service/ReadPartTimeEmploymentPermitDetailService.java
  src/main/java/com/inglo/giggle/document/application/service/ReadStandardLaborContractService.java
  src/main/java/com/inglo/giggle/document/application/service/ReadUserDocumentSummaryUseCaseService.java
  src/main/java/com/inglo/giggle/document/application/service/UpdateOwnerDocumentStatusSubmissionService.java
  src/main/java/com/inglo/giggle/document/application/service/UpdateOwnerPartTimeEmploymentPermitService.java
  src/main/java/com/inglo/giggle/document/application/service/UpdateOwnerStandardLaborContractService.java
  src/main/java/com/inglo/giggle/document/application/service/UpdateUserDocumentStatusRequestionService.java
  src/main/java/com/inglo/giggle/document/application/service/UpdateUserDocumentStatusSubmissionService.java
  src/main/java/com/inglo/giggle/document/application/service/UpdateUserIntegratedApplicationService.java
  src/main/java/com/inglo/giggle/document/application/service/UpdateUserPartTimeEmploymentPermitService.java
  src/main/java/com/inglo/giggle/document/application/service/UpdateUserStandardLaborContractService.java
  src/main/java/com/inglo/giggle/document/application/usecase/CreateUserIntegratedApplicationUseCase.java
  src/main/java/com/inglo/giggle/document/application/usecase/CreateUserPartTimeEmploymentPermitUseCase.java
  src/main/java/com/inglo/giggle/document/application/usecase/CreateUserStandardLaborContractUseCase.java
  src/main/java/com/inglo/giggle/document/application/usecase/ReadIntegratedApplicationDetailUseCase.java
  src/main/java/com/inglo/giggle/document/application/usecase/ReadPartTimeEmploymentPermitDetailUseCase.java
  src/main/java/com/inglo/giggle/document/application/usecase/ReadStandardLaborContractDetailUseCase.java
  src/main/java/com/inglo/giggle/document/application/usecase/UpdateOwnerDocumentStatusSubmissionUseCase.java
  src/main/java/com/inglo/giggle/document/application/usecase/UpdateUserDocumentStatusRequestionUseCase.java
  src/main/java/com/inglo/giggle/document/domain/service/IntegratedApplicationService.java
  src/main/java/com/inglo/giggle/document/domain/service/PartTimeEmploymentPermitService.java
  src/main/java/com/inglo/giggle/document/domain/service/StandardLaborContractService.java
  src/main/java/com/inglo/giggle/document/repository/mysql/DocumentRepository.java
Labels: 🔨 Refactor, 🐾 dongkyeomjang

#54 ✨ Feature - 2.9 회원탈퇴 구현
  http/auth/AuthControllerHttpRequest.http
  src/main/java/com/inglo/giggle/account/domain/Owner.java
  src/main/java/com/inglo/giggle/account/domain/User.java
  src/main/java/com/inglo/giggle/document/domain/Document.java
  src/main/java/com/inglo/giggle/document/domain/IntegratedApplication.java
  src/main/java/com/inglo/giggle/posting/domain/JobPosting.java
  src/main/java/com/inglo/giggle/posting/domain/UserOwnerJobPosting.java
  src/main/java/com/inglo/giggle/resume/domain/Resume.java
  src/main/java/com/inglo/giggle/security/application/controller/AuthController.java
  src/main/java/com/inglo/giggle/security/application/service/DeleteAccountService.java
  src/main/java/com/inglo/giggle/security/application/usecase/DeleteAccountUseCase.java
Labels: ✨ Feature, 🐾 dongkyeomjang

#55 🐞 BugFix - API_4.1, 4.3 Query Error
  http/posting/PostControllerHttpRequest.http
  src/main/java/com/inglo/giggle/posting/application/controller/query/PostingQueryV1Controller.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadJobPostingDetailResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadJobPostingOverviewResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/service/ReadGuestJobPostingOverviewsService.java
  src/main/java/com/inglo/giggle/posting/application/service/ReadJobPostingOverviewService.java
  src/main/java/com/inglo/giggle/posting/application/usecase/ReadJobPostingOverviewUseCase.java
  src/main/java/com/inglo/giggle/posting/repository/mysql/JobPostingRepository.java
Labels: 🐞 BugFix, 🦖 jjuuuunnii

#58 🐞 BugFix - Proxy Error
  http/posting/PostControllerHttpRequest.http
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadJobPostingDetailResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/service/ReadGuestJobPostingOverviewsService.java
  src/main/java/com/inglo/giggle/posting/application/service/ReadJobPostingDetailService.java
  src/main/java/com/inglo/giggle/posting/application/service/ReadJobPostingOverviewService.java
  src/main/java/com/inglo/giggle/posting/domain/JobPosting.java
  src/main/java/com/inglo/giggle/posting/repository/mysql/BookMarkRepository.java
Labels: 🐞 BugFix, 🦖 jjuuuunnii

#61 🐞 BugFix - 7.1 Resume NOT FOUND ERROR
  src/main/java/com/inglo/giggle/account/application/service/ReadUserSummaryService.java
  src/main/java/com/inglo/giggle/posting/application/service/ReadUserJobPostingBriefService.java
  src/main/java/com/inglo/giggle/posting/application/service/ReadUserJobPostingValidationService.java
  src/main/java/com/inglo/giggle/resume/application/service/ReadOwnerResumeDetailService.java
  src/main/java/com/inglo/giggle/resume/domain/service/EducationService.java
  src/main/java/com/inglo/giggle/resume/repository/mysql/EducationRepository.java
  src/main/java/com/inglo/giggle/school/application/service/ReadUserSchoolDetailService.java
Labels: 🐞 BugFix, 🐾 dongkyeomjang

#62 🐞 BugFix - LazyLoadingError
  src/main/java/com/inglo/giggle/resume/application/service/ReadOwnerResumeDetailService.java
  src/main/java/com/inglo/giggle/resume/repository/mysql/ResumeRepository.java
Labels: 🐞 BugFix, 🐾 dongkyeomjang

#67 🐞BugFix - API-4.6 (고용주) 공고에 대한 지원자 리스트 조회 수정
  http/posting/PostControllerHttpRequest.http
  src/main/java/com/inglo/giggle/posting/application/controller/query/PostingOwnersQueryV1Controller.java
  src/main/java/com/inglo/giggle/posting/application/controller/query/PostingUsersQueryV1Controller.java
  src/main/java/com/inglo/giggle/posting/application/service/ReadOwnersJobPostingUserOwnerJobPostingUserOverviewsService.java
  src/main/java/com/inglo/giggle/posting/application/usecase/ReadOwnersJobPostingUserOwnerJobPostingUserOverviewsUseCase.java
  src/main/java/com/inglo/giggle/posting/repository/mysql/UserOwnerJobPostingRepository.java
Labels: 🐞 BugFix, 🦖 jjuuuunnii
