Repository Team-inglo/Giggle-Server, pull requests merged in 2024-11, with the labels that each got.

#69 🔨 Refactor - 4.6 API Sotring
  src/main/java/com/inglo/giggle/posting/application/controller/query/PostingOwnersQueryV1Controller.java
  src/main/java/com/inglo/giggle/posting/application/service/ReadOwnersJobPostingUserOwnerJobPostingUserOverviewsService.java
Labels: 🐞 BugFix, 🦖 jjuuuunnii

#70 ✨ Feature - Notification API (10번대) 구현
  http/notification/NotificationControllerHttpRequest.http
  src/main/java/com/inglo/giggle/account/domain/Owner.java
  src/main/java/com/inglo/giggle/account/domain/User.java
  src/main/java/com/inglo/giggle/core/config/KafkaConfig.java
  src/main/java/com/inglo/giggle/core/listener/NotificationListener.java
  src/main/java/com/inglo/giggle/core/type/EKafkaStatus.java
  src/main/java/com/inglo/giggle/core/type/ENotificationType.java
  src/main/java/com/inglo/giggle/core/utility/DateTimeUtil.java
  src/main/java/com/inglo/giggle/document/application/controller/command/DocumentOwnersCommandV1Controller.java
  src/main/java/com/inglo/giggle/document/application/service/UpdateOwnerPartTimeEmploymentPermitService.java
  src/main/java/com/inglo/giggle/document/application/service/UpdateOwnerStandardLaborContractService.java
  src/main/java/com/inglo/giggle/document/application/service/UpdateUserDocumentStatusRequestionService.java
  src/main/java/com/inglo/giggle/notification/application/controller/command/NotificationCommandV1Controller.java
  src/main/java/com/inglo/giggle/notification/application/controller/query/NotificationQueryV1Controller.java
  src/main/java/com/inglo/giggle/notification/application/dto/ReadNotificationOverviewResponseDto.java
  src/main/java/com/inglo/giggle/notification/application/service/ReadNotificationOverviewService.java
  src/main/java/com/inglo/giggle/notification/application/service/UpdateNotificationIsReadService.java
  src/main/java/com/inglo/giggle/notification/application/usecase/ReadNotificationOverviewUseCase.java
  src/main/java/com/inglo/giggle/notification/application/usecase/UpdateNotificationIsReadUseCase.java
  src/main/java/com/inglo/giggle/notification/domain/Notification.java
  src/main/java/com/inglo/giggle/notification/domain/service/NotificationEventService.java
  src/main/java/com/inglo/giggle/notification/domain/service/NotificationService.java
  src/main/java/com/inglo/giggle/notification/event/NotificationEvent.java
  src/main/java/com/inglo/giggle/notification/repository/mysql/NotificationRepository.java
  src/main/java/com/inglo/giggle/posting/application/service/CreateOwnerJobPostingService.java
  src/main/java/com/inglo/giggle/posting/application/service/CreateUserJobPostingService.java
  src/main/java/com/inglo/giggle/posting/application/service/UpdateOwnerUserOwnerJobPostingStepResumeUnderReviewService.java
  src/main/java/com/inglo/giggle/posting/application/service/UpdateOwnerUserOwnerJobPostingStepWaitingForInterviewService.java
  src/main/java/com/inglo/giggle/posting/application/service/UpdateUserUserOwnerJobPostingStepApplicationInProgressService.java
  src/main/java/com/inglo/giggle/posting/application/service/UpdateUserUserOwnerJobPostingStepFillingOutDocumentsService.java
  src/main/java/com/inglo/giggle/posting/domain/JobPosting.java
  src/main/java/com/inglo/giggle/security/domain/mysql/Account.java
Labels: ✨ Feature, 🦖 jjuuuunnii

#73 🔨 Refactor - 공고 등록 time값 수정
  src/main/java/com/inglo/giggle/posting/application/service/CreateOwnerJobPostingService.java
  src/main/java/com/inglo/giggle/posting/application/service/UpdateOwnerJobPostingService.java
Labels: 🔨 Refactor, 🦖 jjuuuunnii

#75 🐞 BugFix - DeadLine Error
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadJobPostingOverviewResponseDto.java
Labels: 🐞 BugFix, 🦖 jjuuuunnii

#77 🐞 BugFix - Null Point Exception + 서류 관련 로직 수정
  src/main/java/com/inglo/giggle/core/constant/Constants.java
  src/main/java/com/inglo/giggle/document/application/dto/response/ReadOwnerDocumentSummaryResponseDto.java
  src/main/java/com/inglo/giggle/document/application/dto/response/ReadPartTimeEmploymentPermitDetailResponseDto.java
  src/main/java/com/inglo/giggle/document/application/dto/response/ReadStandardLaborContractDetailResponseDto.java
  src/main/java/com/inglo/giggle/document/application/service/ConfirmUserDocumentService.java
  src/main/java/com/inglo/giggle/document/application/service/CreateUserIntegratedApplicationService.java
  src/main/java/com/inglo/giggle/document/application/service/ReadStandardLaborContractService.java
  src/main/java/com/inglo/giggle/document/application/service/UpdateUserDocumentStatusSubmissionService.java
  src/main/java/com/inglo/giggle/document/application/service/UpdateUserIntegratedApplicationService.java
  src/main/java/com/inglo/giggle/document/domain/service/IntegratedApplicationService.java
  src/main/java/com/inglo/giggle/document/domain/service/PartTimeEmploymentPermitService.java
  src/main/java/com/inglo/giggle/document/domain/service/StandardLaborContractService.java
Labels: 🐞 BugFix, 🐾 dongkyeomjang
