Repository Team-inglo/Giggle-Server, pull requests merged in 2025-05, with the labels that each got.

#284 🌏 Deploy - Krampoline -> AWS Migration
  .github/workflows/ci.yml
  .github/workflows/dev-cicd.yml
  .github/workflows/prod-cicd.yml
  build.gradle
  dev.Dockerfile
  krampoline.Dockerfile
  prod.Dockerfile
  src/main/resources/application.yml
Labels: 🌏 Deploy, 🐾 dongkyeomjang

#286 🌏 Deploy - firebase-key.json 볼륨마운트
  .github/workflows/dev-cicd.yml
  .github/workflows/prod-cicd.yml
Labels: 🌏 Deploy, 🐾 dongkyeomjang

#293 ✨ Feature - 희망근로조건 기능 추가
  http/resume/ResumeControllerHttpRequest.http
  src/main/java/com/inglo/giggle/core/exception/error/ErrorCode.java
  src/main/java/com/inglo/giggle/posting/domain/type/EJobCategory.java
  src/main/java/com/inglo/giggle/resume/application/dto/request/CreateUserWorkPreferenceRequestDto.java
  src/main/java/com/inglo/giggle/resume/application/dto/request/UpdateUserWorkPreferenceRequestDto.java
  src/main/java/com/inglo/giggle/resume/application/dto/response/ReadAdminResumeDetailResponseDtoV2.java
  src/main/java/com/inglo/giggle/resume/application/dto/response/ReadOwnerResumeDetailResponseDtoV2.java
  src/main/java/com/inglo/giggle/resume/application/dto/response/ReadUserResumeDetailResponseDtoV2.java
  src/main/java/com/inglo/giggle/resume/application/dto/response/ReadUserWorkPreferenceDetailResponseDto.java
  src/main/java/com/inglo/giggle/resume/application/service/CreateUserWorkPreferenceService.java
  src/main/java/com/inglo/giggle/resume/application/service/DeleteUserWorkPreferenceService.java
  src/main/java/com/inglo/giggle/resume/application/service/ReadAdminResumeDetailService.java
  src/main/java/com/inglo/giggle/resume/application/service/ReadOwnerResumeDetailService.java
  src/main/java/com/inglo/giggle/resume/application/service/ReadUserResumeDetailService.java
  src/main/java/com/inglo/giggle/resume/application/service/ReadUserWorkPreferenceDetailService.java
  src/main/java/com/inglo/giggle/resume/application/service/UpdateUserWorkPreferenceService.java
  src/main/java/com/inglo/giggle/resume/application/usecase/CreateUserWorkPreferenceUseCase.java
  src/main/java/com/inglo/giggle/resume/application/usecase/DeleteUserWorkPreferenceUseCase.java
  src/main/java/com/inglo/giggle/resume/application/usecase/ReadUserWorkPreferenceDetailUseCase.java
  src/main/java/com/inglo/giggle/resume/application/usecase/UpdateUserWorkPreferenceUseCase.java
  src/main/java/com/inglo/giggle/resume/controller/command/ResumeUsersCommandV1Controller.java
  src/main/java/com/inglo/giggle/resume/controller/query/ResumeUsersQueryV1Controller.java
  src/main/java/com/inglo/giggle/resume/domain/Resume.java
  src/main/java/com/inglo/giggle/resume/domain/WorkPreference.java
  src/main/java/com/inglo/giggle/resume/repository/WorkPreferenceRepository.java
  src/main/java/com/inglo/giggle/resume/repository/impl/WorkPreferenceRepositoryImpl.java
  src/main/java/com/inglo/giggle/resume/repository/mysql/WorkPreferenceJpaRepository.java
Labels: ✨ Feature, 🐾 dongkyeomjang

#295 ♻️ Refactor: 메일 형식 변경 및 메일 전송 방식 SMTP로 변경
  http/auth/AuthControllerHttpRequest.http
  src/main/java/com/inglo/giggle/core/event/listener/EmailListener.java
  src/main/java/com/inglo/giggle/core/utility/MailUtil.java
Labels: ♻️ Refactor, 🐾 dongkyeomjang

#297 🔨 Fix - WorkPreference 요구사항에 맞게 변경
  http/auth/AuthControllerHttpRequest.http
  http/resume/ResumeControllerHttpRequest.http
  src/main/java/com/inglo/giggle/resume/application/dto/request/CreateUserWorkPreferenceRequestDto.java
  src/main/java/com/inglo/giggle/resume/application/dto/request/UpdateUserWorkPreferenceRequestDto.java
  src/main/java/com/inglo/giggle/resume/application/dto/response/ReadAdminResumeDetailResponseDtoV2.java
  src/main/java/com/inglo/giggle/resume/application/dto/response/ReadOwnerResumeDetailResponseDtoV2.java
  src/main/java/com/inglo/giggle/resume/application/dto/response/ReadUserResumeDetailResponseDtoV2.java
  src/main/java/com/inglo/giggle/resume/application/dto/response/ReadUserWorkPreferenceDetailResponseDto.java
  src/main/java/com/inglo/giggle/resume/application/service/CreateUserWorkPreferenceService.java
  src/main/java/com/inglo/giggle/resume/application/service/DeleteUserWorkPreferenceService.java
  src/main/java/com/inglo/giggle/resume/application/service/ReadAdminResumeDetailService.java
  src/main/java/com/inglo/giggle/resume/application/service/ReadOwnerResumeDetailService.java
  src/main/java/com/inglo/giggle/resume/application/service/ReadUserResumeDetailService.java
  src/main/java/com/inglo/giggle/resume/application/service/ReadUserWorkPreferenceDetailService.java
  src/main/java/com/inglo/giggle/resume/application/service/UpdateUserWorkPreferenceService.java
  src/main/java/com/inglo/giggle/resume/application/usecase/CreateUserWorkPreferenceUseCase.java
  src/main/java/com/inglo/giggle/resume/application/usecase/DeleteUserWorkPreferenceUseCase.java
  src/main/java/com/inglo/giggle/resume/application/usecase/ReadUserWorkPreferenceDetailUseCase.java
  src/main/java/com/inglo/giggle/resume/application/usecase/UpdateUserWorkPreferenceUseCase.java
  src/main/java/com/inglo/giggle/resume/controller/command/ResumeUsersCommandV1Controller.java
  src/main/java/com/inglo/giggle/resume/controller/query/ResumeUsersQueryV1Controller.java
  src/main/java/com/inglo/giggle/resume/domain/PreferenceAddress.java
  src/main/java/com/inglo/giggle/resume/domain/Resume.java
  src/main/java/com/inglo/giggle/resume/domain/WorkPreference.java
  src/main/java/com/inglo/giggle/resume/repository/WorkPreferenceRepository.java
  src/main/java/com/inglo/giggle/resume/repository/impl/WorkPreferenceRepositoryImpl.java
  src/main/java/com/inglo/giggle/resume/repository/mysql/WorkPreferenceJpaRepository.java
  src/main/java/com/inglo/giggle/security/application/service/SignUpDefaultUserService.java
Labels: 🔨 Fix, 🐾 dongkyeomjang

#300 🔨 Fix: 커리어 조회 시 sorting value TRENDING -> POPULAR 변경
  http/resume/ResumeControllerHttpRequest.http
  src/main/java/com/inglo/giggle/career/application/service/ReadGuestCareersOverviewsService.java
  src/main/java/com/inglo/giggle/career/application/service/ReadUserCareersOverviewsService.java
Labels: 🔨 Fix, 🐾 dongkyeomjang

#303 🔨 Fix: Career 조회 시 Visa Lazy Loading 해결
  src/main/java/com/inglo/giggle/career/application/service/ReadGuestsCareersDetailsService.java
  src/main/java/com/inglo/giggle/career/application/service/ReadUsersCareersDetailsService.java
Labels: 🔨 Fix, 🦖 jjuuuunnii

#306 🔨 Fix: EJobCategory 수정
  src/main/java/com/inglo/giggle/career/application/dto/request/CreateAdminsCareerRequestDto.java
  src/main/java/com/inglo/giggle/posting/domain/type/EJobCategory.java
Labels: 🔨 Fix, 🦖 jjuuuunnii

#309 ✨ Feature: 이력서 공개/비공개 컬럼 추가 및 이력서 북마크 도메인 추가
  src/main/java/com/inglo/giggle/resume/domain/BookMarkResume.java
  src/main/java/com/inglo/giggle/resume/domain/Resume.java
  src/main/java/com/inglo/giggle/resume/repository/BookMarkResumeRepository.java
  src/main/java/com/inglo/giggle/resume/repository/impl/BookMarkResumeRepositoryImpl.java
  src/main/java/com/inglo/giggle/resume/repository/mysql/BookMarkResumeJpaRepository.java
Labels: ✨ Feature, 🦖 jjuuuunnii

#311 ✨ Feature: 7.1 API 수정 및 7.23, 15.1 API 생성
  http/auth/AuthControllerHttpRequest.http
  http/resume/ResumeControllerHttpRequest.http
  src/main/java/com/inglo/giggle/resume/application/dto/request/UpdateUserResumeIsPublicRequestDto.java
  src/main/java/com/inglo/giggle/resume/application/dto/response/ReadUserResumeDetailResponseDtoV1.java
  src/main/java/com/inglo/giggle/resume/application/dto/response/ReadUserResumeDetailResponseDtoV2.java
  src/main/java/com/inglo/giggle/resume/application/dto/response/UpdateOwnerResumeBookMarkResumeResponseDto.java
  src/main/java/com/inglo/giggle/resume/application/dto/response/UpdateUserResumeIsPublicResponseDto.java
  src/main/java/com/inglo/giggle/resume/application/service/UpdateOwnerResumeBookMarkResumeService.java
  src/main/java/com/inglo/giggle/resume/application/service/UpdateUserResumeIsPublicService.java
  src/main/java/com/inglo/giggle/resume/application/usecase/UpdateOwnerResumeBookMarkResumeUseCase.java
  src/main/java/com/inglo/giggle/resume/application/usecase/UpdateUserResumeIsPublicUseCase.java
  src/main/java/com/inglo/giggle/resume/controller/command/ResumeOwnersCommandV1Controller.java
  src/main/java/com/inglo/giggle/resume/controller/command/ResumeUsersCommandV1Controller.java
  src/main/java/com/inglo/giggle/resume/domain/BookMarkResume.java
  src/main/java/com/inglo/giggle/resume/repository/BookMarkResumeRepository.java
  src/main/java/com/inglo/giggle/resume/repository/impl/BookMarkResumeRepositoryImpl.java
  src/main/java/com/inglo/giggle/resume/repository/mysql/BookMarkResumeJpaRepository.java
Labels: ✨ Feature, 🦖 jjuuuunnii
