Repository Team-inglo/Giggle-Server, pull requests merged in 2025-01, with the labels that each got.

#89 🔨 Refactor - 각 서류 워드파일만 제공으로 변경
  http/posting/PostControllerHttpRequest.http
  src/main/java/com/inglo/giggle/document/application/controller/query/DocumentOwnersQueryV1Controller.java
  src/main/java/com/inglo/giggle/document/application/dto/response/ReadOwnerDocumentSummaryResponseDto.java
  src/main/java/com/inglo/giggle/document/application/dto/response/ReadUserDocumentSummaryResponseDto.java
  src/main/java/com/inglo/giggle/document/application/service/ConfirmUserDocumentService.java
  src/main/java/com/inglo/giggle/document/application/service/CreateUserIntegratedApplicationService.java
  src/main/java/com/inglo/giggle/document/application/service/ReadOwnerDocumentSummaryService.java
  src/main/java/com/inglo/giggle/document/application/service/UpdateUserIntegratedApplicationService.java
  src/main/java/com/inglo/giggle/document/application/usecase/ReadOwnerDocumentSummaryUseCase.java
  src/main/java/com/inglo/giggle/document/domain/service/DocumentService.java
Labels: 🔨 Refactor, 🐾 dongkyeomjang

#92 ✨ Feature - 카프카 리스너 제거 및 RestApI로 변경
  build.gradle
  src/main/java/com/inglo/giggle/core/config/KafkaConfig.java
  src/main/java/com/inglo/giggle/core/listener/NotificationListener.java
  src/main/java/com/inglo/giggle/core/utility/JsonParseUtil.java
  src/main/java/com/inglo/giggle/core/utility/RestClientUtil.java
  src/main/java/com/inglo/giggle/posting/application/service/ReadUserJobPostingBriefService.java
  src/main/java/com/inglo/giggle/posting/application/service/ReadUserJobPostingValidationService.java
Labels: ✨ Feature

#93 ✨ Feature - 약관 조회 및 약관 동의 API 구현
  http/auth/AuthControllerHttpRequest.http
  http/term/TermControllerHttpRequest.http
  src/main/java/com/inglo/giggle/security/application/dto/request/SignUpDefaultOwnerRequestDto.java
  src/main/java/com/inglo/giggle/security/application/dto/request/SignUpDefaultUserRequestDto.java
  src/main/java/com/inglo/giggle/security/application/service/SignUpDefaultOwnerService.java
  src/main/java/com/inglo/giggle/security/application/service/SignUpDefaultUserService.java
  src/main/java/com/inglo/giggle/term/application/controller/command/TermCommandV1Controller.java
  src/main/java/com/inglo/giggle/term/application/controller/consumer/.keep
  src/main/java/com/inglo/giggle/term/application/controller/query/TermQueryV1Controller.java
  src/main/java/com/inglo/giggle/term/application/dto/request/CreateTermAccountRequestDto.java
  src/main/java/com/inglo/giggle/term/application/dto/response/ReadTermDetailResponseDto.java
  src/main/java/com/inglo/giggle/term/application/service/CreateTermAccountService.java
  src/main/java/com/inglo/giggle/term/application/service/ReadTermDetailService.java
  src/main/java/com/inglo/giggle/term/application/usecase/CreateTermAccountUseCase.java
  src/main/java/com/inglo/giggle/term/application/usecase/ReadTermDetailUseCase.java
  src/main/java/com/inglo/giggle/term/domain/Term.java
  src/main/java/com/inglo/giggle/term/domain/TermAccount.java
  src/main/java/com/inglo/giggle/term/domain/service/TermAccountService.java
  src/main/java/com/inglo/giggle/term/domain/type/ETermType.java
  src/main/java/com/inglo/giggle/term/repository/mysql/TermAccountRepository.java
  src/main/java/com/inglo/giggle/term/repository/mysql/TermRepository.java
  src/main/java/com/inglo/giggle/term/repository/redis/.keep
Labels: ✨ Feature, 🐾 dongkyeomjang

#98 🐞 BugFix: 재검토 요청이 두 개 이상일때의 버그 수정
  src/main/java/com/inglo/giggle/document/application/service/ConfirmUserDocumentService.java
  src/main/java/com/inglo/giggle/document/application/service/ReadOwnerDocumentSummaryService.java
  src/main/java/com/inglo/giggle/document/domain/Document.java
  src/main/java/com/inglo/giggle/document/domain/Reject.java
  src/main/java/com/inglo/giggle/document/repository/mysql/RejectRepository.java
  template/~$tegrated-application.doc
Labels: 🐞 BugFix, 🐾 dongkyeomjang

#99 🐞 BugFix: 재검토 요청이 두 개 이상일때의 버그 수정
  src/main/java/com/inglo/giggle/document/application/service/ConfirmUserDocumentService.java
  src/main/java/com/inglo/giggle/document/repository/mysql/RejectRepository.java
Labels: 🐞 BugFix, 🐾 dongkyeomjang

#101 🔨 Refactor - 불필요 로깅 제거
  src/main/java/com/inglo/giggle/posting/application/service/ReadGuestJobPostingOverviewsService.java
Labels: 🔨 Refactor, 🐾 dongkyeomjang

#103 🔨 Refactor - 11.1 약관 정보 상세 조회 Public으로 변경
  src/main/java/com/inglo/giggle/core/constant/Constants.java
Labels: 🔨 Refactor, 🐾 dongkyeomjang

#105 🔨 Refactor - Reject에 AutoGenerated Id 추가
  src/main/java/com/inglo/giggle/document/application/service/ConfirmUserDocumentService.java
  src/main/java/com/inglo/giggle/document/application/service/ReadOwnerDocumentSummaryService.java
  src/main/java/com/inglo/giggle/document/domain/Reject.java
  src/main/java/com/inglo/giggle/document/repository/mysql/RejectRepository.java
Labels: 🔨 Refactor, 🐾 dongkyeomjang

#107 🐞 BugFix - Term 조회 버그 해결
  src/main/java/com/inglo/giggle/term/application/service/ReadTermDetailService.java
  src/main/java/com/inglo/giggle/term/repository/mysql/TermRepository.java
Labels: 🐞 BugFix, 🐾 dongkyeomjang

#109 🐞 BugFix - Account에 One To Many로 TermAccount가 걸려있지 않아, 회원탈퇴가 되지 않던 버그 수정
  http/DeleteScenario.http
  http/TestScenarioOne.http
  http/TestScenarioTwo.http
  http/auth/AuthControllerHttpRequest.http
  src/main/java/com/inglo/giggle/security/domain/mysql/Account.java
  template/part-time-employment-permit.doc
  template/~$tegrated-application.doc
Labels: 🐞 BugFix, 🐾 dongkyeomjang

#111 📃 Docs - add template on .gitignore
  .gitignore
  template/integrated-application.doc
  template/integrated-application.hwp
  template/part-time-employment-permit.doc
  template/part-time-employment-permit.hwp
  template/standard-labor-contract.docx
  template/standard-labor-contract.hwp
Labels: 📃 Docs, 🐾 dongkyeomjang

#113 🐞 BugFix - 시간제 취업 허가서 호환성 버그 해결
  build.gradle
  http/TestScenarioOne.http
  http/TestScenarioOneEnd.http
  http/TestScenarioTwo.http
  http/auth/AuthControllerHttpRequest.http
  src/main/java/com/inglo/giggle/address/domain/Address.java
  src/main/java/com/inglo/giggle/document/domain/service/PartTimeEmploymentPermitService.java
  src/main/java/com/inglo/giggle/document/domain/service/StandardLaborContractService.java
Labels: 🐞 BugFix, 🐾 dongkyeomjang

#115 🐞 BugFix - 시간제 취업허가서 서명 위치가 어긋나있는 버그 수정
  src/main/java/com/inglo/giggle/document/domain/service/PartTimeEmploymentPermitService.java
Labels: 🐞 BugFix, 🐾 dongkyeomjang

#117 🐞 BugFix - 통합 신청서 서명이 없어야 할 위치에도 존재하던 버그 수정
  http/TestScenarioTwo.http
  src/main/java/com/inglo/giggle/core/constant/Constants.java
  src/main/java/com/inglo/giggle/document/application/service/UpdateUserIntegratedApplicationService.java
  src/main/java/com/inglo/giggle/document/domain/service/IntegratedApplicationService.java
  src/main/java/com/inglo/giggle/document/domain/service/PartTimeEmploymentPermitService.java
Labels: 🐞 BugFix, 🐾 dongkyeomjang

#119 🐞 BugFix - 검색 쿼리 Distinct와 GroupBy의 혼용으로 인한 버그 수정
  src/main/java/com/inglo/giggle/posting/repository/mysql/JobPostingRepository.java
Labels: 🐞 BugFix, 🐾 dongkyeomjang
