Repository Team-inglo/Giggle-Server, pull requests merged in 2025-02, with the labels that each got.

#122 ✨ Feature - 디바이스 토큰 업데이트 API 구현
  http/auth/AuthControllerHttpRequest.http
  src/main/java/com/inglo/giggle/security/application/controller/AuthController.java
  src/main/java/com/inglo/giggle/security/application/dto/request/UpdateDeviceTokenRequestDto.java
  src/main/java/com/inglo/giggle/security/application/service/UpdateDeviceTokenService.java
  src/main/java/com/inglo/giggle/security/application/usecase/UpdateDeviceTokenUseCase.java
  src/main/java/com/inglo/giggle/security/domain/mysql/Account.java
  src/main/java/com/inglo/giggle/security/domain/service/AccountService.java
Labels: ✨ Feature, 🐾 dongkyeomjang

#123 ✨ Feature - 3.1 유저 정보 조회에 주소 추가
  src/main/java/com/inglo/giggle/account/application/dto/response/ReadUserDetailResponseDto.java
Labels: ✨ Feature, 🐾 dongkyeomjang

#125 🌏 Deploy - Private Docker Hub 사용에 필요한 플로우 추가
  .github/ISSUE_TEMPLATE/bugFix.md
  .github/ISSUE_TEMPLATE/crossBrowsing.md
  .github/ISSUE_TEMPLATE/deploy.md
  .github/ISSUE_TEMPLATE/docs.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/ISSUE_TEMPLATE/setting.md
  .github/ISSUE_TEMPLATE/test.md
  .github/workflows/dev-cicd.yml
Labels: 🌏 Deploy, 🐾 dongkyeomjang

#127 📃 Docs - 이슈 템플릿 이모지 변경
  .github/ISSUE_TEMPLATE/bugFix.md
  .github/ISSUE_TEMPLATE/fix.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/pull_request_template.md
Labels: 📃 Docs

#129 🔨 Fix - 2.5 기본 유저 회원가입에 address, nationality, birth 값 optional로 변경
  src/main/java/com/inglo/giggle/account/domain/User.java
  src/main/java/com/inglo/giggle/address/domain/service/AddressService.java
  src/main/java/com/inglo/giggle/security/application/controller/AuthController.java
  src/main/java/com/inglo/giggle/security/application/dto/request/SignUpDefaultUserRequestDto.java
  src/main/java/com/inglo/giggle/security/application/service/SignUpDefaultUserService.java
Labels: 🔨 Fix, 🐾 dongkyeomjang

#131 🔨 Fix - 3.1 유저 프로필 조회하기에 address, nationality, birth 세 값 null 반환 허용
  src/main/java/com/inglo/giggle/account/application/dto/response/ReadUserDetailResponseDto.java
Labels: 🔨 Fix, 🐾 dongkyeomjang

#133 🔨 Fix - 3.3 유저 요약 정보 조회하기 address, nationality, birth 세 값 null 반환 허용
  src/main/java/com/inglo/giggle/account/application/dto/response/ReadUserSummaryResponseDto.java
Labels: 🔨 Fix, 🐾 dongkyeomjang

#135 🔨 Fix - 3.5 프로필 수정하기에 address, nationality, birth 세 값 null 허용
  src/main/java/com/inglo/giggle/account/application/dto/request/UpdateUserRequestDto.java
  src/main/java/com/inglo/giggle/account/domain/service/UserService.java
Labels: 🔨 Fix, 🐾 dongkyeomjang

#137 🔨 Fix - 7.1 이력서 조회하기에 address, nationality, birth 세 값 null 허용
  src/main/java/com/inglo/giggle/resume/application/dto/response/ReadUserResumeDetailResponseDto.java
Labels: 🔨 Fix, 🐾 dongkyeomjang

#140 📃 Docs - Update Readme
  README.md
Labels: 📃 Docs, 🐾 dongkyeomjang

#141 🔨 Fix - 7.19 이력서 조회하기에 address, nationality, birth 세 값 null 허용
  src/main/java/com/inglo/giggle/resume/application/dto/response/ReadOwnerResumeDetailResponseDto.java
Labels: 🔨 Fix, 🐾 dongkyeomjang

#143 🔨 Fix - 4.8 공고 지원자격 확인하기 항상 True 반환하도록 변경
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadUserJobPostingValidationResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/service/ReadUserJobPostingValidationService.java
Labels: 🔨 Fix, 🐾 dongkyeomjang

#146 ✨ Feature - 2.11 비밀번호 변경 API 구현
  http/auth/AuthControllerHttpRequest.http
  src/main/java/com/inglo/giggle/core/constant/Constants.java
  src/main/java/com/inglo/giggle/core/exception/error/ErrorCode.java
  src/main/java/com/inglo/giggle/security/application/controller/AuthController.java
  src/main/java/com/inglo/giggle/security/application/dto/request/ChangePasswordRequestDto.java
  src/main/java/com/inglo/giggle/security/application/service/ChangePasswordService.java
  src/main/java/com/inglo/giggle/security/application/service/ReissueAuthenticationCodeService.java
  src/main/java/com/inglo/giggle/security/application/service/ReissuePasswordService.java
  src/main/java/com/inglo/giggle/security/application/usecase/ChangePasswordUseCase.java
Labels: ✨ Feature, 🐾 dongkyeomjang

#148 🔨 Fix - 7.1, 7.19 이력서 조회에 필드 추가
  src/main/java/com/inglo/giggle/resume/application/dto/response/ReadOwnerResumeDetailResponseDto.java
  src/main/java/com/inglo/giggle/resume/application/dto/response/ReadUserResumeDetailResponseDto.java
Labels: 🔨 Fix, 🐾 dongkyeomjang

#149 🔨 Fix - 7.1, 7.19 이력서 조회 Birth 반환 형식 변경
  src/main/java/com/inglo/giggle/core/utility/DateTimeUtil.java
  src/main/java/com/inglo/giggle/resume/application/dto/response/ReadOwnerResumeDetailResponseDto.java
  src/main/java/com/inglo/giggle/resume/application/dto/response/ReadUserResumeDetailResponseDto.java
Labels: 🔨 Fix, 🐾 dongkyeomjang

#151 🔨 Fix - 아이디와 이메일 통합
  src/main/java/com/inglo/giggle/security/application/dto/request/SignUpDefaultTemporaryRequestDto.java
Labels: 🔨 Fix, 🐾 dongkyeomjang

#154 🔨 Fix - Main화변 변경으로 인한 공고 조회 시 데이터 추가
  http/posting/PostControllerHttpRequest.http
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadGuestJobPostingOverviewsResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadJobPostingOverviewResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/service/ReadGuestJobPostingOverviewsService.java
  src/main/java/com/inglo/giggle/posting/application/service/ReadJobPostingOverviewService.java
  src/main/java/com/inglo/giggle/posting/domain/JobPosting.java
  src/main/java/com/inglo/giggle/posting/repository/mysql/JobPostingRepository.java
Labels: 🔨 Fix, 🐾 dongkyeomjang

#156 🔨 Fix - companyName 필드 추가
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadGuestJobPostingOverviewsResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadJobPostingOverviewResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/service/ReadGuestJobPostingOverviewsService.java
Labels: 🔨 Fix, 🐾 dongkyeomjang

#157 ♻️ Refactor: 푸시알림 서버 변경 및 시큐리티 로직 변경
  http/auth/AuthControllerHttpRequest.http
  src/main/java/com/inglo/giggle/account/domain/Owner.java
  src/main/java/com/inglo/giggle/account/domain/User.java
  src/main/java/com/inglo/giggle/account/domain/service/OwnerService.java
  src/main/java/com/inglo/giggle/account/domain/service/UserService.java
  src/main/java/com/inglo/giggle/core/constant/Constants.java
  src/main/java/com/inglo/giggle/core/event/dto/DeregisterDeviceTokenEventDto.java
  src/main/java/com/inglo/giggle/core/event/dto/NotificationEventDto.java
  src/main/java/com/inglo/giggle/core/event/dto/UpdateDeviceTokenEventDto.java
  src/main/java/com/inglo/giggle/core/event/listener/EmailListener.java
  src/main/java/com/inglo/giggle/core/event/listener/NotificationListener.java
  src/main/java/com/inglo/giggle/core/listener/NotificationListener.java
  src/main/java/com/inglo/giggle/core/utility/HeaderUtil.java
  src/main/java/com/inglo/giggle/core/utility/JsonParseUtil.java
  src/main/java/com/inglo/giggle/core/utility/RestClientUtil.java
  src/main/java/com/inglo/giggle/document/application/service/UpdateOwnerPartTimeEmploymentPermitService.java
  src/main/java/com/inglo/giggle/document/application/service/UpdateOwnerStandardLaborContractService.java
  src/main/java/com/inglo/giggle/document/application/service/UpdateUserDocumentStatusRequestionService.java
  src/main/java/com/inglo/giggle/notification/domain/service/NotificationEventService.java
  src/main/java/com/inglo/giggle/notification/event/NotificationEvent.java
  src/main/java/com/inglo/giggle/posting/application/service/CreateUserJobPostingService.java
  src/main/java/com/inglo/giggle/posting/application/service/UpdateOwnerUserOwnerJobPostingStepResumeUnderReviewService.java
  src/main/java/com/inglo/giggle/posting/application/service/UpdateOwnerUserOwnerJobPostingStepWaitingForInterviewService.java
  src/main/java/com/inglo/giggle/posting/application/service/UpdateUserUserOwnerJobPostingStepApplicationInProgressService.java
  src/main/java/com/inglo/giggle/posting/application/service/UpdateUserUserOwnerJobPostingStepFillingOutDocumentsService.java
  src/main/java/com/inglo/giggle/security/application/controller/AuthController.java
  src/main/java/com/inglo/giggle/security/application/dto/request/IssueAuthenticationCodeRequestDto.java
  src/main/java/com/inglo/giggle/security/application/dto/request/SignUpDefaultTemporaryRequestDto.java
  src/main/java/com/inglo/giggle/security/application/dto/request/UpdateDeviceTokenRequestDto.java
  src/main/java/com/inglo/giggle/security/application/dto/request/ValidateAuthenticationCodeRequestDto.java
  src/main/java/com/inglo/giggle/security/application/service/ReissueAuthenticationCodeService.java
  src/main/java/com/inglo/giggle/security/application/service/ReissuePasswordService.java
  src/main/java/com/inglo/giggle/security/application/service/SignUpDefaultOwnerService.java
  src/main/java/com/inglo/giggle/security/application/service/SignUpDefaultTemporaryService.java
  src/main/java/com/inglo/giggle/security/application/service/SignUpDefaultUserService.java
  src/main/java/com/inglo/giggle/security/application/service/UpdateDeviceTokenService.java
  src/main/java/com/inglo/giggle/security/application/service/ValidateAuthenticationCodeService.java
  src/main/java/com/inglo/giggle/security/application/service/ValidateIdService.java
  src/main/java/com/inglo/giggle/security/application/usecase/UpdateDeviceTokenUseCase.java
  src/main/java/com/inglo/giggle/security/application/usecase/ValidateIdUseCase.java
  src/main/java/com/inglo/giggle/security/domain/mysql/Account.java
  src/main/java/com/inglo/giggle/security/domain/mysql/AccountDevice.java
  src/main/java/com/inglo/giggle/security/domain/redis/TemporaryAccount.java
  src/main/java/com/inglo/giggle/security/domain/redis/TemporaryToken.java
  src/main/java/com/inglo/giggle/security/domain/service/AccountDeviceService.java
  src/main/java/com/inglo/giggle/security/domain/service/AccountService.java
  src/main/java/com/inglo/giggle/security/domain/service/TemporaryTokenService.java
  src/main/java/com/inglo/giggle/security/repository/mysql/AccountDeviceRepository.java
  src/main/java/com/inglo/giggle/security/repository/mysql/AccountRepository.java
  src/main/java/com/inglo/giggle/security/repository/redis/TemporaryAccountRepository.java
Labels: ♻️ Refactor, 🦖 jjuuuunnii

#175 🔨Fix: Dockerfile, Yaml 베이스 이미지 변경
  Dockerfile
  k8s/mysql.yaml
  k8s/redis.yaml
Labels: 🔨 Fix

#180 ✨ Feature - 2.12 현재 비밀번호 확인 API 구현
  http/auth/AuthControllerHttpRequest.http
  src/main/java/com/inglo/giggle/core/constant/Constants.java
  src/main/java/com/inglo/giggle/security/application/controller/AuthController.java
  src/main/java/com/inglo/giggle/security/application/dto/request/ValidatePasswordRequestDto.java
  src/main/java/com/inglo/giggle/security/application/dto/response/ValidatePasswordResponseDto.java
  src/main/java/com/inglo/giggle/security/application/service/ValidatePasswordService.java
  src/main/java/com/inglo/giggle/security/application/usecase/ValidatePasswordUseCase.java
Labels: ✨ Feature, 🐾 dongkyeomjang

#182 ✨ Feature: 2.5, 2.6 유저, 고용주 회원가입시 토큰 발급
  http/auth/AuthControllerHttpRequest.http
  src/main/java/com/inglo/giggle/core/utility/S3Util.java
  src/main/java/com/inglo/giggle/security/application/controller/AuthController.java
  src/main/java/com/inglo/giggle/security/application/service/SignUpDefaultOwnerService.java
  src/main/java/com/inglo/giggle/security/application/service/SignUpDefaultUserService.java
  src/main/java/com/inglo/giggle/security/application/usecase/SignUpDefaultOwnerUseCase.java
  src/main/java/com/inglo/giggle/security/application/usecase/SignUpDefaultUserUseCase.java
Labels: ✨ Feature, 🦖 jjuuuunnii

#188 🌏 Deploy - cicd.yml 삭제
  .github/workflows/dev-cicd.yml
Labels: 🌏 Deploy, 🐾 dongkyeomjang

#192 🔨 Fix - 마감된 공고에 대한 지원 시 예외처리 추가
  src/main/java/com/inglo/giggle/core/exception/error/ErrorCode.java
  src/main/java/com/inglo/giggle/posting/application/service/CreateUserJobPostingService.java
  src/main/java/com/inglo/giggle/posting/application/service/ReadJobPostingOverviewService.java
Labels: 🔨 Fix, 🐾 dongkyeomjang

#195 🔨 Fix - 회원가입 시 비밀번호 특수문자 Validation 변경
  src/main/java/com/inglo/giggle/core/utility/PasswordUtil.java
  src/main/java/com/inglo/giggle/security/application/dto/request/ChangePasswordRequestDto.java
  src/main/java/com/inglo/giggle/security/application/dto/request/SignUpDefaultTemporaryRequestDto.java
Labels: 🔨 Fix, 🐾 dongkyeomjang
