Repository Team-inglo/Giggle-Server, pull requests merged in 2025-06, with the labels that each got.

#315 🔨 Fix - JobCategory LazyLoading 문제 해결 + 북마크 여부 필드 추가
  http/resume/ResumeControllerHttpRequest.http
  src/main/java/com/inglo/giggle/resume/application/dto/response/ReadOwnerResumeDetailByResumeIdResponseDto.java
  src/main/java/com/inglo/giggle/resume/application/dto/response/ReadOwnerResumeOverviewResponseDto.java
  src/main/java/com/inglo/giggle/resume/application/service/ReadOwnerResumeDetailService.java
  src/main/java/com/inglo/giggle/resume/application/usecase/ReadOwnerResumeDetailUseCase.java
  src/main/java/com/inglo/giggle/resume/controller/query/ResumeOwnersQueryV1Controller.java
  src/main/java/com/inglo/giggle/resume/repository/ResumeRepository.java
  src/main/java/com/inglo/giggle/resume/repository/impl/ResumeRepositoryImpl.java
  src/main/java/com/inglo/giggle/resume/repository/mysql/ResumeJpaRepository.java
Labels: 🔨 Fix, 🐾 dongkyeomjang

#317 🔨 Fix - 7.24 address 필드 추가 및 query param: is-book-marked 추가
  http/auth/AuthControllerHttpRequest.http
  http/resume/ResumeControllerHttpRequest.http
  src/main/java/com/inglo/giggle/resume/application/dto/response/ReadOwnerResumeDetailByResumeIdResponseDto.java
  src/main/java/com/inglo/giggle/resume/application/dto/response/ReadOwnerResumeOverviewResponseDto.java
  src/main/java/com/inglo/giggle/resume/application/service/ReadOwnerResumeOverviewService.java
  src/main/java/com/inglo/giggle/resume/application/usecase/ReadOwnerResumeOverviewUseCase.java
  src/main/java/com/inglo/giggle/resume/controller/query/ResumeOwnersQueryV1Controller.java
  src/main/java/com/inglo/giggle/resume/repository/ResumeRepository.java
  src/main/java/com/inglo/giggle/resume/repository/impl/ResumeRepositoryImpl.java
Labels: 🔨 Fix, 🐾 dongkyeomjang

#320 ✨ Feature: 어드민 커리어 API 구현 및 4.6 API DTO 수정
  http/career/CarrerControllerHttpRequest.http
  src/main/java/com/inglo/giggle/career/application/dto/request/UpdateAdminsCareerRequestDto.java
  src/main/java/com/inglo/giggle/career/application/dto/response/ReadAdminsCareersDetailsResponseDto.java
  src/main/java/com/inglo/giggle/career/application/dto/response/ReadAdminsCareersOverviewsResponseDto.java
  src/main/java/com/inglo/giggle/career/application/service/CreateAdminsCareerService.java
  src/main/java/com/inglo/giggle/career/application/service/DeleteAdminsCareerService.java
  src/main/java/com/inglo/giggle/career/application/service/ReadAdminsCareersDetailsService.java
  src/main/java/com/inglo/giggle/career/application/service/ReadAdminsCareersOverviewsService.java
  src/main/java/com/inglo/giggle/career/application/service/UpdateAdminsCareerService.java
  src/main/java/com/inglo/giggle/career/application/usecase/DeleteAdminsCareerUseCase.java
  src/main/java/com/inglo/giggle/career/application/usecase/ReadAdminsCareersDetailsUseCase.java
  src/main/java/com/inglo/giggle/career/application/usecase/ReadAdminsCareersOverviewsUseCase.java
  src/main/java/com/inglo/giggle/career/application/usecase/UpdateAdminsCareerUseCase.java
  src/main/java/com/inglo/giggle/career/controller/command/CareerAdminsCommandV1Controller.java
  src/main/java/com/inglo/giggle/career/controller/query/CareerAdminQueryV1Controller.java
  src/main/java/com/inglo/giggle/career/domain/Career.java
  src/main/java/com/inglo/giggle/career/domain/CareerImage.java
  src/main/java/com/inglo/giggle/career/repository/CareerImageRepository.java
  src/main/java/com/inglo/giggle/career/repository/CareerRepository.java
  src/main/java/com/inglo/giggle/career/repository/impl/CareerImageRepositoryImpl.java
  src/main/java/com/inglo/giggle/career/repository/impl/CareerRepositoryImpl.java
  src/main/java/com/inglo/giggle/career/repository/mysql/CareerImageJpaRepository.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadOwnersJobPostingUserOwnerJobPostingUserOverviewsResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/service/UpdateOwnerJobPostingService.java
Labels: ✨ Feature, 🦖 jjuuuunnii

#323 🔨 Fix - Lob 어노테이션 붙은 컬럼들 속성 TEXT로 변경
  http/career/CarrerControllerHttpRequest.http
  src/main/java/com/inglo/giggle/career/domain/Career.java
  src/main/java/com/inglo/giggle/career/domain/CareerImage.java
  src/main/java/com/inglo/giggle/posting/domain/CompanyImage.java
Labels: 🔨 Fix, 🐾 dongkyeomjang

#325 🔨 Fix - ENationality, EMajor fromString에 맵핑되는 value값을 Enum.name으로 변경
  src/main/java/com/inglo/giggle/core/type/EMajor.java
  src/main/java/com/inglo/giggle/core/type/ENationality.java
Labels: 🔨 Fix, 🐾 dongkyeomjang

#328 🔨 Fix - ENationality가 Blank 인 경우 처리
  src/main/java/com/inglo/giggle/core/type/ENationality.java
Labels: 🔨 Fix, 🐾 dongkyeomjang

#331 ♻️ Refactor: 14.1, 14.3 API ResponseDto 수정
  src/main/java/com/inglo/giggle/career/application/dto/response/ReadGuestsCareersOverviewsResponseDto.java
  src/main/java/com/inglo/giggle/career/application/dto/response/ReadUsersCareersOverviewsResponseDto.java
  src/main/java/com/inglo/giggle/career/application/service/ReadGuestCareersOverviewsService.java
  src/main/java/com/inglo/giggle/career/application/service/ReadUserCareersOverviewsService.java
Labels: ♻️ Refactor, 🦖 jjuuuunnii
