Repository Team-inglo/Giggle-Server, pull requests merged in 2025-03, with the labels that each got.

#199 ✨ Feature - Account에 Admin Role 추가, Banner API 구현
  http/auth/AuthControllerHttpRequest.http
  http/banner/BannerControllerHttpRequest.http
  k8s/api-server.yaml
  src/main/java/com/inglo/giggle/account/domain/Admin.java
  src/main/java/com/inglo/giggle/address/domain/Address.java
  src/main/java/com/inglo/giggle/banner/application/controller/command/BannerAdminCommandV1Controller.java
  src/main/java/com/inglo/giggle/banner/application/controller/consumer/.keep
  src/main/java/com/inglo/giggle/banner/application/controller/query/BannerGuestQueryV1Controller.java
  src/main/java/com/inglo/giggle/banner/application/controller/query/BannerQueryV1Controller.java
  src/main/java/com/inglo/giggle/banner/application/dto/request/CreateAdminBannerRequestDto.java
  src/main/java/com/inglo/giggle/banner/application/dto/response/ReadBannerDetailResponseDto.java
  src/main/java/com/inglo/giggle/banner/application/dto/response/ReadBannerOverviewResponseDto.java
  src/main/java/com/inglo/giggle/banner/application/service/CreateAdminBannerService.java
  src/main/java/com/inglo/giggle/banner/application/service/DeleteAdminBannerService.java
  src/main/java/com/inglo/giggle/banner/application/service/ReadBannerDetailService.java
  src/main/java/com/inglo/giggle/banner/application/service/ReadBannerOverviewService.java
  src/main/java/com/inglo/giggle/banner/application/service/ReadGuestBannerDetailService.java
  src/main/java/com/inglo/giggle/banner/application/service/ReadGuestBannerOverviewService.java
  src/main/java/com/inglo/giggle/banner/application/usecase/CreateAdminBannerUseCase.java
  src/main/java/com/inglo/giggle/banner/application/usecase/DeleteAdminBannerUseCase.java
  src/main/java/com/inglo/giggle/banner/application/usecase/ReadBannerDetailUseCase.java
  src/main/java/com/inglo/giggle/banner/application/usecase/ReadBannerOverviewUseCase.java
  src/main/java/com/inglo/giggle/banner/application/usecase/ReadGuestBannerDetailUseCase.java
  src/main/java/com/inglo/giggle/banner/application/usecase/ReadGuestBannerOverviewUseCase.java
  src/main/java/com/inglo/giggle/banner/domain/Banner.java
  src/main/java/com/inglo/giggle/banner/domain/service/.keep
  src/main/java/com/inglo/giggle/banner/domain/type/.keep
  src/main/java/com/inglo/giggle/banner/repository/mysql/BannerRepository.java
  src/main/java/com/inglo/giggle/banner/repository/redis/.keep
  src/main/java/com/inglo/giggle/core/annotation/security/Role.java
  src/main/java/com/inglo/giggle/core/config/WebMVCConfig.java
  src/main/java/com/inglo/giggle/core/resolver/HttpRoleArgumentResolver.java
  src/main/java/com/inglo/giggle/core/type/EImageType.java
  src/main/java/com/inglo/giggle/core/utility/S3Util.java
  src/main/java/com/inglo/giggle/posting/application/service/CreateUserJobPostingService.java
  src/main/java/com/inglo/giggle/security/config/AdminConfig.java
  src/main/java/com/inglo/giggle/security/config/SecurityConfig.java
  src/main/java/com/inglo/giggle/security/domain/service/AccountService.java
  src/main/java/com/inglo/giggle/security/domain/type/ESecurityRole.java
  src/main/java/com/inglo/giggle/security/handler/login/DefaultLoginSuccessHandler.java
  src/main/resources/application-krampoline.yml
Labels: ✨ Feature, 🐾 dongkyeomjang

#201 🔨 Fix - 공고 등록 및 수정 시, 비자 다중으로 받도록 수정
  http/TestScenarioOne.http
  http/posting/PostControllerHttpRequest.http
  src/main/java/com/inglo/giggle/core/type/EVisa.java
  src/main/java/com/inglo/giggle/posting/application/controller/query/PostingGuestsQueryV1Controller.java
  src/main/java/com/inglo/giggle/posting/application/controller/query/PostingQueryV1Controller.java
  src/main/java/com/inglo/giggle/posting/application/dto/request/CreateOwnerJobPostingRequestDto.java
  src/main/java/com/inglo/giggle/posting/application/dto/request/UpdateOwnerJobPostingRequestDto.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadGuestJobPostingDetailResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadJobPostingDetailResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadUserBookMarkOverviewResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/service/ReadGuestJobPostingOverviewsService.java
  src/main/java/com/inglo/giggle/posting/application/service/ReadJobPostingOverviewService.java
  src/main/java/com/inglo/giggle/posting/application/usecase/ReadGuestJobPostingOverviewsUseCase.java
  src/main/java/com/inglo/giggle/posting/application/usecase/ReadJobPostingOverviewUseCase.java
  src/main/java/com/inglo/giggle/posting/domain/JobPosting.java
  src/main/java/com/inglo/giggle/posting/domain/service/JobPostingService.java
  src/main/java/com/inglo/giggle/posting/repository/mysql/JobPostingRepository.java
Labels: 🔨 Fix, 🐾 dongkyeomjang

#202 ♻️ Refactor: Security 권한 분리
  src/main/java/com/inglo/giggle/core/config/WebMVCConfig.java
  src/main/java/com/inglo/giggle/core/constant/Constants.java
  src/main/java/com/inglo/giggle/core/interceptor/pre/HttpAccountIDInterceptor.java
  src/main/java/com/inglo/giggle/security/config/SecurityConfig.java
  src/main/java/com/inglo/giggle/security/filter/JsonWebTokenAuthenticationFilter.java
Labels: ♻️ Refactor, 🦖 jjuuuunnii

#204 🔨 Fix - 쿼리 변수가 포함된 NO_NEED_URL 적용 안되는 버그 수정
  src/main/java/com/inglo/giggle/security/config/SecurityConfig.java
  src/main/java/com/inglo/giggle/security/matcher/CustomRegexRequestMatcher.java
  src/main/resources/application-krampoline.yml
Labels: 🔨 Fix, 🐾 dongkyeomjang

#206 🔨Fix: Regex 수정 및 Interceptor 로직 변경
  src/main/java/com/inglo/giggle/core/constant/Constants.java
  src/main/java/com/inglo/giggle/core/dto/ResponseDto.java
  src/main/java/com/inglo/giggle/core/exception/handler/HttpGlobalExceptionHandler.java
  src/main/java/com/inglo/giggle/core/interceptor/pre/HttpAccountIDInterceptor.java
  src/main/java/com/inglo/giggle/security/config/SecurityConfig.java
  src/main/java/com/inglo/giggle/security/matcher/CustomRegexRequestMatcher.java
Labels: 🔨 Fix, 🦖 jjuuuunnii

#208 🔨Fix: Interceptor 로직 수정
  src/main/java/com/inglo/giggle/core/config/WebMVCConfig.java
  src/main/java/com/inglo/giggle/core/interceptor/pre/HttpAccountIDInterceptor.java
Labels: 🔨 Fix, 🦖 jjuuuunnii

#210 🔨 Fix - 비자 잘못된 배열로 가는 오류 수정 / 비자 종류 추가
  .github/workflows/ci.yml
  src/main/java/com/inglo/giggle/core/type/EVisa.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadGuestJobPostingOverviewsResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadJobPostingOverviewResponseDto.java
  src/main/resources/application-krampoline.yml
Labels: 🔨 Fix, 🐾 dongkyeomjang

#212 🔨Fix: 공고 조회시 Lazy Loading
  k8s/api-server.yaml
  src/main/java/com/inglo/giggle/posting/repository/mysql/JobPostingRepository.java
Labels: 🔨 Fix, 🦖 jjuuuunnii

#214 🔨 Fix: Nationality Null Check & 4.7 API ResponseDto 수정
  src/main/java/com/inglo/giggle/account/application/dto/response/ReadUserDetailResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadJobPostingSummariesResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadOwnerUserJobPostingDetailResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadOwnerUserOwnerJobPostingDetailResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadOwnersJobPostingUserOwnerJobPostingUserOverviewsResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/service/ReadJobPostingSummariesService.java
Labels: 🔨 Fix, 🦖 jjuuuunnii

#216 🔨 Fix - 6.1 6.6 응답 데이터 변경
  k8s/api-server.yaml
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadOwnerJobPostingOverviewsResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadUserUserOwnerJobPostingListResponseDto.java
Labels: 🔨 Fix, 🐾 dongkyeomjang

#218 🔨 Fix - RequestBody에 Valid가 제대로 적용되지 않는 문제 수정
  http/auth/AuthControllerHttpRequest.http
  src/main/java/com/inglo/giggle/account/application/dto/request/UpdateOwnerRequestDto.java
  src/main/java/com/inglo/giggle/account/application/dto/request/UpdateUserRequestDto.java
  src/main/java/com/inglo/giggle/document/application/dto/request/CreateUserIntegratedApplicationRequestDto.java
  src/main/java/com/inglo/giggle/document/application/dto/request/CreateUserStandardLaborContractRequestDto.java
  src/main/java/com/inglo/giggle/document/application/dto/request/UpdateOwnerPartTimeEmploymentPermitRequestDto.java
  src/main/java/com/inglo/giggle/document/application/dto/request/UpdateOwnerStandardLaborContractRequestDto.java
  src/main/java/com/inglo/giggle/document/application/dto/request/UpdateUserIntegratedApplicationRequestDto.java
  src/main/java/com/inglo/giggle/document/application/dto/request/UpdateUserStandardLaborContractRequestDto.java
  src/main/java/com/inglo/giggle/notification/application/dto/ReadNotificationOverviewResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/dto/request/CreateOwnerJobPostingRequestDto.java
  src/main/java/com/inglo/giggle/posting/application/dto/request/UpdateOwnerJobPostingRequestDto.java
  src/main/java/com/inglo/giggle/security/application/dto/request/SignUpDefaultOwnerRequestDto.java
  src/main/java/com/inglo/giggle/security/application/dto/request/SignUpDefaultUserRequestDto.java
Labels: 🔨 Fix, 🐾 dongkyeomjang

#221 🔨 Fix - 공고 상세조회에 누락된 연령제한 필드 추가
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadGuestJobPostingDetailResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadJobPostingDetailResponseDto.java
Labels: 🔨 Fix, 🐾 dongkyeomjang

#226 ✨ Feature - Soft Delete 적용
  src/main/java/com/inglo/giggle/account/domain/Owner.java
  src/main/java/com/inglo/giggle/account/domain/User.java
  src/main/java/com/inglo/giggle/banner/domain/Banner.java
  src/main/java/com/inglo/giggle/core/dto/BaseEntity.java
  src/main/java/com/inglo/giggle/document/domain/ContractWorkDayTime.java
  src/main/java/com/inglo/giggle/document/domain/Document.java
  src/main/java/com/inglo/giggle/document/domain/IntegratedApplication.java
  src/main/java/com/inglo/giggle/document/domain/PartTimeEmploymentPermit.java
  src/main/java/com/inglo/giggle/document/domain/Reject.java
  src/main/java/com/inglo/giggle/document/domain/StandardLaborContract.java
  src/main/java/com/inglo/giggle/notification/domain/Notification.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadOwnerUserJobPostingDetailResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadOwnerUserOwnerJobPostingDetailResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadUserUserOwnerJobPostingDetailResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadUserUserOwnerJobPostingListResponseDto.java
  src/main/java/com/inglo/giggle/posting/domain/BookMark.java
  src/main/java/com/inglo/giggle/posting/domain/CompanyImage.java
  src/main/java/com/inglo/giggle/posting/domain/JobPosting.java
  src/main/java/com/inglo/giggle/posting/domain/PostingWorkDayTime.java
  src/main/java/com/inglo/giggle/posting/domain/UserOwnerJobPosting.java
  src/main/java/com/inglo/giggle/resume/domain/AdditionalLanguage.java
  src/main/java/com/inglo/giggle/resume/domain/Education.java
  src/main/java/com/inglo/giggle/resume/domain/LanguageSkill.java
  src/main/java/com/inglo/giggle/resume/domain/Resume.java
  src/main/java/com/inglo/giggle/resume/domain/WorkExperience.java
  src/main/java/com/inglo/giggle/school/domain/School.java
  src/main/java/com/inglo/giggle/security/domain/mysql/Account.java
  src/main/java/com/inglo/giggle/security/domain/mysql/AccountDevice.java
  src/main/java/com/inglo/giggle/term/domain/Term.java
  src/main/java/com/inglo/giggle/term/domain/TermAccount.java
Labels: ✨ Feature, 🐾 dongkyeomjang

#229 🔨 Fix - region4_depth validation 오류 수정
  src/main/java/com/inglo/giggle/address/dto/request/AddressRequestDto.java
Labels: 🔨 Fix, 🐾 dongkyeomjang

#230 ✨ Feature: 디스코드 에러 웹훅 연결 구현
  k8s/api-server.yaml
  src/main/java/com/inglo/giggle/core/event/dto/SendDiscordEventDto.java
  src/main/java/com/inglo/giggle/core/event/listener/DiscordListener.java
  src/main/java/com/inglo/giggle/core/exception/handler/ExceptionCatchHandler.java
  src/main/java/com/inglo/giggle/core/exception/handler/HttpGlobalExceptionHandler.java
  src/main/java/com/inglo/giggle/core/utility/HeaderUtil.java
  src/main/java/com/inglo/giggle/core/utility/RestClientUtil.java
  src/main/resources/application-krampoline.yml
Labels: ✨ Feature, 🦖 jjuuuunnii

#236 ✨ Feature - (관리자) 약관 생성 API 구현
  http/term/TermControllerHttpRequest.http
  src/main/java/com/inglo/giggle/banner/application/controller/command/BannerAdminsCommandV1Controller.java
  src/main/java/com/inglo/giggle/banner/application/controller/query/BannerGuestsQueryV1Controller.java
  src/main/java/com/inglo/giggle/term/application/controller/command/TermAdminsCommandV1Controller.java
  src/main/java/com/inglo/giggle/term/application/dto/request/CreateAdminTermAccountRequestDto.java
  src/main/java/com/inglo/giggle/term/application/service/CreateAdminTermAccountService.java
  src/main/java/com/inglo/giggle/term/application/usecase/CreateAdminTermAccountUseCase.java
  src/main/resources/application-krampoline.yml
Labels: ✨ Feature, 🐾 dongkyeomjang

#239 ✨ Feature - 무중단 배포를 위한 의존성 추가 및 yaml에 설정 추가
  build.gradle
  k8s/api-server.yaml
  src/main/resources/application-krampoline.yml
Labels: ✨ Feature, 🐾 dongkyeomjang

#242 ✨ Feature: (관리자) 4번대, 6번대 API 구현
  http/account/AccountControllerHttpRequest.http
  http/auth/AuthControllerHttpRequest.http
  http/posting/PostControllerHttpRequest.http
  src/main/java/com/inglo/giggle/posting/application/controller/command/PostingAdminsCommandV1Controller.java
  src/main/java/com/inglo/giggle/posting/application/controller/query/PostingAdminQueryV1Controller.java
  src/main/java/com/inglo/giggle/posting/application/controller/query/PostingUsersQueryV1Controller.java
  src/main/java/com/inglo/giggle/posting/application/dto/request/UpdateAdminUserOwnerJobPostingMemoRequestDto.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadAdminJobPostingsOverviewsResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadAdminJobPostingsSummariesResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadAdminUserOwnerJobPostingsApplicationSuccessSummariesResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadAdminUserOwnerJobPostingsBriefsResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadAdminUserOwnerJobPostingsDigestsResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadAdminUserOwnerJobPostingsOverviewsResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadAdminUserOwnerJobPostingsSummariesResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/service/ReadAdminJobPostingsOverviewsService.java
  src/main/java/com/inglo/giggle/posting/application/service/ReadAdminJobPostingsSummariesService.java
  src/main/java/com/inglo/giggle/posting/application/service/ReadAdminUserOwnerJobPostingsApplicationSuccessSummariesService.java
  src/main/java/com/inglo/giggle/posting/application/service/ReadAdminUserOwnerJobPostingsBriefsService.java
  src/main/java/com/inglo/giggle/posting/application/service/ReadAdminUserOwnerJobPostingsDigestsService.java
  src/main/java/com/inglo/giggle/posting/application/service/ReadAdminUserOwnerJobPostingsOverviewsService.java
  src/main/java/com/inglo/giggle/posting/application/service/ReadAdminUserOwnerJobPostingsSummariesService.java
  src/main/java/com/inglo/giggle/posting/application/service/UpdateAdminUserOwnerJobPostingMemoService.java
  src/main/java/com/inglo/giggle/posting/application/usecase/ReadAdminJobPostingsOverviewsUseCase.java
  src/main/java/com/inglo/giggle/posting/application/usecase/ReadAdminJobPostingsSummariesUseCase.java
  src/main/java/com/inglo/giggle/posting/application/usecase/ReadAdminUserOwnerJobPostingsApplicationSuccessSummariesUseCase.java
  src/main/java/com/inglo/giggle/posting/application/usecase/ReadAdminUserOwnerJobPostingsBriefsUseCase.java
  src/main/java/com/inglo/giggle/posting/application/usecase/ReadAdminUserOwnerJobPostingsDigestsUseCase.java
  src/main/java/com/inglo/giggle/posting/application/usecase/ReadAdminUserOwnerJobPostingsOverviewsUseCase.java
  src/main/java/com/inglo/giggle/posting/application/usecase/ReadAdminUserOwnerJobPostingsSummariesUseCase.java
  src/main/java/com/inglo/giggle/posting/application/usecase/UpdateAdminUserOwnerJobPostingMemoUseCase.java
  src/main/java/com/inglo/giggle/posting/domain/type/EApplicationStep.java
  src/main/java/com/inglo/giggle/posting/repository/mysql/JobPostingQueryRepository.java
  src/main/java/com/inglo/giggle/posting/repository/mysql/JobPostingQueryRepositoryImpl.java
  src/main/java/com/inglo/giggle/posting/repository/mysql/JobPostingRepository.java
  src/main/java/com/inglo/giggle/posting/repository/mysql/UserOwnerJobPostingQueryRepository.java
  src/main/java/com/inglo/giggle/posting/repository/mysql/UserOwnerJobPostingRepository.java
  src/main/java/com/inglo/giggle/posting/repository/mysql/UserOwnerJobPostingRepositoryImpl.java
Labels: ✨ Feature, 🦖 jjuuuunnii

#250 🔨 Fix - updatedAt이 null인 경우 nullPointException 문제 해결
  src/main/java/com/inglo/giggle/core/exception/handler/HttpGlobalExceptionHandler.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadOwnerUserJobPostingDetailResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadOwnersJobPostingUserOwnerJobPostingUserOverviewsResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadUserUserOwnerJobPostingDetailResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadUserUserOwnerJobPostingListResponseDto.java
  src/main/java/com/inglo/giggle/resume/application/dto/request/UpdateUserSejongInstituteReqeustDto.java
  src/main/java/com/inglo/giggle/resume/application/dto/request/UpdateUserTopikReqeustDto.java
Labels: 🔨 Fix, 🐾 dongkyeomjang

#252 🔨 Fix - NullPointException 버그 해결
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadOwnerUserJobPostingDetailResponseDto.java
  src/main/java/com/inglo/giggle/posting/application/dto/response/ReadOwnerUserOwnerJobPostingDetailResponseDto.java
Labels: 🔨 Fix, 🐾 dongkyeomjang

#254 🔨Fix: 공고 검색시 북마크가 전체 조회되는 이슈
  src/main/java/com/inglo/giggle/posting/application/service/ReadJobPostingOverviewService.java
  src/main/java/com/inglo/giggle/posting/repository/JobPostingRepository.java
  src/main/java/com/inglo/giggle/posting/repository/impl/JobPostingRepositoryImpl.java
  src/main/java/com/inglo/giggle/posting/repository/mysql/JobPostingJpaRepository.java
Labels: 🔨 Fix, 🦖 jjuuuunnii

#256 🔨 Fix: 파일 수정시 Url Encoding
  src/main/java/com/inglo/giggle/core/utility/S3Util.java
Labels: 🔨 Fix, 🦖 jjuuuunnii

#258 ✨ Feature - 서류 생성 시, 이미 존재하는 서류에 대한 예외처리 기능 추가
  http/account/AccountControllerHttpRequest.http
  src/main/java/com/inglo/giggle/document/application/service/CreateUserIntegratedApplicationService.java
  src/main/java/com/inglo/giggle/document/application/service/CreateUserPartTimeEmploymentPermitService.java
  src/main/java/com/inglo/giggle/document/application/service/CreateUserStandardLaborContractService.java
Labels: ✨ Feature, 🐾 dongkyeomjang

#260 🔨 Fix: Education & WorkExperience 생성 및 수정 Validation 추가
  src/main/java/com/inglo/giggle/core/exception/error/ErrorCode.java
  src/main/java/com/inglo/giggle/resume/application/dto/request/CreateUserEducationRequestDto.java
  src/main/java/com/inglo/giggle/resume/application/dto/request/CreateUserWorkExperienceRequestDto.java
  src/main/java/com/inglo/giggle/resume/application/dto/request/UpdateUserEducationRequestDto.java
  src/main/java/com/inglo/giggle/resume/application/dto/request/UpdateUserWorkExperienceRequestDto.java
  src/main/java/com/inglo/giggle/resume/controller/command/ResumeUsersCommandV1Controller.java
Labels: 🔨 Fix, 🦖 jjuuuunnii

#262 🔨 Fix: DeviceToken 생성 및 업데이트 DTO, 로직 수정
  src/main/java/com/inglo/giggle/security/application/dto/request/UpdateDeviceTokenRequestDto.java
  src/main/java/com/inglo/giggle/security/application/service/UpdateDeviceTokenService.java
Labels: 🔨 Fix, 🦖 jjuuuunnii

#264 🔨 Fix: 로그아웃 시 AccountDevice 삭제 추가
  src/main/java/com/inglo/giggle/security/application/service/LogoutService.java
  src/main/java/com/inglo/giggle/security/repository/AccountDeviceRepository.java
  src/main/java/com/inglo/giggle/security/repository/impl/AccountDeviceRepositoryImpl.java
  src/main/java/com/inglo/giggle/security/repository/mysql/AccountDeviceJpaRepository.java
Labels: 🔨 Fix, 🦖 jjuuuunnii

#266 🔨 Fix - WorkExperience 삭제 구문 오타 수정
  src/main/java/com/inglo/giggle/resume/domain/WorkExperience.java
Labels: 🔨 Fix, 🐾 dongkyeomjang

#268 ✨ Feature: Admin 관련 API Security 적용
  src/main/java/com/inglo/giggle/core/constant/Constants.java
Labels: ✨ Feature, 🦖 jjuuuunnii

#270 🔨 Fix: Reissue Token 로직 수정
  src/main/java/com/inglo/giggle/security/application/service/ReissueJsonWebTokenService.java
  src/main/java/com/inglo/giggle/security/repository/RefreshTokenRepository.java
  src/main/java/com/inglo/giggle/security/repository/impl/RefreshTokenRepositoryImpl.java
  src/main/java/com/inglo/giggle/security/repository/redis/RefreshTokenRedisRepository.java
Labels: 🔨 Fix, 🦖 jjuuuunnii

#272 🔨 Fix: 카카오 푸시알림 FCM으로 변경
  .gitignore
  build.gradle
  k8s/api-server.yaml
  src/main/java/com/inglo/giggle/core/event/dto/DeregisterDeviceTokenEventDto.java
  src/main/java/com/inglo/giggle/core/event/dto/UpdateDeviceTokenEventDto.java
  src/main/java/com/inglo/giggle/core/event/listener/NotificationListener.java
  src/main/java/com/inglo/giggle/core/exception/error/ErrorCode.java
  src/main/java/com/inglo/giggle/core/postConstruct/FireBasePostConstruct.java
  src/main/java/com/inglo/giggle/security/application/service/UpdateDeviceTokenService.java
  src/main/resources/application-krampoline.yml
Labels: 🔨 Fix, 🦖 jjuuuunnii

#274 ✨ Feature: Version 도메인 세팅 및 0.1 최신 버전 조회하기 API 구현
  http/auth/AuthControllerHttpRequest.http
  http/posting/PostControllerHttpRequest.http
  http/version/VersionControllerHttpRequest.http
  src/main/java/com/inglo/giggle/core/constant/Constants.java
  src/main/java/com/inglo/giggle/core/exception/error/ErrorCode.java
  src/main/java/com/inglo/giggle/version/application/dto/response/ReadRecentVersionResponseDto.java
  src/main/java/com/inglo/giggle/version/application/service/ReadRecentVersionService.java
  src/main/java/com/inglo/giggle/version/application/usecase/ReadRecentVersionUseCase.java
  src/main/java/com/inglo/giggle/version/controller/query/VersionQueryV1Controller.java
  src/main/java/com/inglo/giggle/version/domain/Version.java
  src/main/java/com/inglo/giggle/version/domain/type/EOsType.java
  src/main/java/com/inglo/giggle/version/repository/VersionRepository.java
  src/main/java/com/inglo/giggle/version/repository/impl/VersionRepositoryImpl.java
  src/main/java/com/inglo/giggle/version/repository/mysql/VersionJpaRepository.java
Labels: ✨ Feature, 🦖 jjuuuunnii
